# Generated by Django 4.1.3 on 2023-03-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetoadmin',
            name='email',
        ),
    ]
