# Generated by Django 4.1.3 on 2023-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0003_contact_us_address_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(related_name='categorize', to='Site_App.articlecategory', verbose_name='دسته بندی ها'),
        ),
    ]
