# Generated by Django 4.1.3 on 2023-03-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0004_alter_article_selected_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'مقالات'},
        ),
    ]
