# Generated by Django 4.1.3 on 2023-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0005_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Slider')),
                ('url_slider', models.URLField()),
                ('in_active', models.BooleanField(default=True)),
            ],
        ),
    ]
