# Generated by Django 4.1.3 on 2023-03-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0006_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ی ما'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'اطلاعات', 'verbose_name_plural': 'اطلاعات تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='messagetoadmin',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
    ]
