# Generated by Django 4.1.3 on 2023-03-15 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0007_alter_about_us_options_alter_contact_us_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='fax',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='id_bale',
            field=models.URLField(verbose_name='لینک بله'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='id_insta',
            field=models.URLField(verbose_name='لینک اینستا'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='id_soroosh',
            field=models.URLField(verbose_name='لینک سروش'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='image_address',
            field=models.ImageField(upload_to='contact_us', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='name_gap',
            field=models.CharField(max_length=200, verbose_name='اسم گروه'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='شماره تلفن'),
        ),
    ]
