# Generated by Django 4.1.3 on 2023-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0008_alter_contact_us_fax_alter_contact_us_id_bale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetoadmin',
            name='is_ready',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='خوانده شده/نشده'),
        ),
    ]
