# Generated by Django 4.1.3 on 2023-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0011_admintouser_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Another',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('url', models.URLField(verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images_site', verbose_name='تصویر')),
                ('type', models.IntegerField(verbose_name='نوع خراش')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت های دیگر',
                'verbose_name_plural': 'اطلاعات سایت های دیگر',
            },
        ),
    ]
