# Generated by Django 4.1.3 on 2023-09-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0012_site_another'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site_Another',
        ),
    ]
