# Generated by Django 4.1.3 on 2023-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0013_delete_site_another'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_scrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('address_element', models.CharField(max_length=200, verbose_name='ادرس المنت')),
                ('image', models.ImageField(upload_to='images_site', verbose_name='تصویر')),
                ('type', models.IntegerField(verbose_name='نوع خراش')),
                ('time_sleep', models.IntegerField(verbose_name='زمان لود ')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت های دیگر',
                'verbose_name_plural': 'اطلاعات سایت های دیگر',
            },
        ),
    ]
