# Generated by Django 4.2.5 on 2023-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0014_site_scrape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_scrape',
            name='time_sleep',
        ),
        migrations.AddField(
            model_name='site_scrape',
            name='type_search',
            field=models.ImageField(default=0, upload_to='', verbose_name='روش جستجو'),
        ),
    ]
