# Generated by Django 4.2.5 on 2023-09-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_App', '0015_remove_site_scrape_time_sleep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_scrape',
            name='type_search',
            field=models.IntegerField(default=0, verbose_name='روش جستجو'),
        ),
    ]
