# Generated by Django 4.1.3 on 2023-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('count_like', models.IntegerField(default=0, verbose_name='تعداد لایک')),
                ('offer_price', models.IntegerField(default=0, verbose_name='تخفیف')),
                ('count_buy', models.IntegerField(default=0)),
                ('count_all', models.IntegerField(default=0, verbose_name='تعداد کل محصولات')),
                ('name_class', models.CharField(choices=[('Pooshak', 'Pooshak'), ('Phone', 'Phone'), ('System', 'System'), ('TV', 'TV'), ('Laundry', 'Laundry'), ('Refrigerator', 'Refrigerator'), ('Headset', 'Headset'), ('Case', 'Case'), ('keyboard', 'Keyboard')], default='System', max_length=30, verbose_name='نام کلاس')),
            ],
            options={
                'verbose_name': 'جزئیات محصول',
                'verbose_name_plural': 'جزئیات محصول',
            },
        ),
    ]
