# Generated by Django 4.1.3 on 2023-02-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='ProductImages', verbose_name='عکس محصول')),
                ('size', models.FloatField(default='', verbose_name='')),
                ('color_code', models.CharField(max_length=20, verbose_name='کد رنگ')),
                ('count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductMain', to='Product.product', verbose_name='محصول مربوطه')),
            ],
        ),
    ]
