# Generated by Django 4.1.3 on 2023-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_detailproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailproduct',
            options={'verbose_name': 'جزئیات محصول', 'verbose_name_plural': 'جزئیات محصولات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصول', 'verbose_name_plural': ' محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
    ]
