# Generated by Django 4.1.3 on 2023-02-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_detailproduct_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproduct',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
