# Generated by Django 4.1.3 on 2023-02-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_brand_product_categorize'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_seri', models.CharField(max_length=100, verbose_name='سری پردازنده')),
                ('ram_capacity', models.IntegerField(verbose_name='ظرفیت RAM')),
                ('ram_type', models.CharField(max_length=10, verbose_name='نوع حافظه')),
                ('GPU_manufacture', models.CharField(max_length=100, verbose_name='شرکت سازنده')),
                ('guarantee_time', models.IntegerField(verbose_name='گارانتی')),
                ('capcity_hard', models.IntegerField()),
                ('weight', models.FloatField()),
                ('system_func', models.CharField(max_length=100)),
                ('number_port', models.IntegerField(default=0)),
                ('connect_door', models.CharField(max_length=100)),
                ('webcam', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='اطلاعات اصلی محصول')),
            ],
            options={
                'verbose_name': 'سیستم',
                'verbose_name_plural': 'سیستم ها',
            },
        ),
    ]
