# Generated by Django 4.1.3 on 2023-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='system',
            name='size_screen',
            field=models.FloatField(default=0),
        ),
    ]
