# Generated by Django 4.1.3 on 2023-02-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_system_model_system_size_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('size_screen', models.FloatField()),
                ('system_type', models.CharField(max_length=20)),
                ('version_system', models.IntegerField()),
                ('weight', models.FloatField()),
                ('number_sim', models.IntegerField()),
                ('hard', models.IntegerField()),
                ('ram_number', models.IntegerField()),
                ('resolvation_image', models.CharField(max_length=100)),
                ('included_items', models.TextField()),
                ('screen_technology', models.CharField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
