# Generated by Django 4.1.3 on 2023-02-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailproduct',
            name='size',
            field=models.FloatField(default='', null=True, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='detailproduct',
            name='unit',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
