# Generated by Django 4.1.3 on 2023-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_detailproduct_size_alter_detailproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailproduct',
            name='color',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
