# Generated by Django 4.1.3 on 2023-02-04 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
