# Generated by Django 4.1.3 on 2023-02-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_soopermarket_alter_product_categorize_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SooperMarket',
        ),
    ]
