# Generated by Django 4.1.3 on 2023-02-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_delete_soopermarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='SooperMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('use', models.TextField()),
                ('boad', models.CharField(max_length=20)),
                ('health_license', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
