# Generated by Django 4.1.3 on 2023-02-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_soopermarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPooshak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pooshak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('Maintenance', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='detailproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='detailproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='detailproduct',
            name='unit',
        ),
        migrations.AlterField(
            model_name='detailproduct',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='SooperMarket',
        ),
        migrations.AddField(
            model_name='detailpooshak',
            name='detail_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.detailproduct'),
        ),
    ]
