# Generated by Django 4.1.3 on 2023-02-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_detailpooshak_pooshak_remove_detailproduct_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpooshak',
            name='detail_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pooshak', to='Product.detailproduct'),
        ),
    ]
