# Generated by Django 4.1.3 on 2023-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_alter_detailpooshak_detail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooshak',
            name='sex',
            field=models.CharField(default='', max_length=100),
        ),
    ]
