# Generated by Django 4.1.3 on 2023-02-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_pooshak_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailPooshak',
        ),
    ]
