# Generated by Django 4.1.3 on 2023-02-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_detailpooshak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorize',
            field=models.CharField(choices=[('Digital', 'کالا دیجیتال'), ('Appliances', 'لوازم برقی'), ('Mantue', 'مانتو'), ('Paltue', 'پالتو'), ('Shoes', 'کفش'), ('Scarf', 'شال و روسری')], default='Digital', max_length=20),
        ),
    ]
