# Generated by Django 4.1.3 on 2023-02-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_alter_product_categorize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('Suitable', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ability', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('Suitable', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('stracture', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('Surface_coverage', models.TextField(blank=True, null=True)),
                ('Ability', models.TextField(blank=True)),
            ],
        ),
    ]
