# Generated by Django 4.1.3 on 2023-02-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_alter_product_name_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('foot', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('chart_energy', models.CharField(max_length=1)),
                ('type_translate_barfak', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('v_Refrigerator', models.FloatField()),
                ('V_freeze', models.FloatField()),
                ('v_all_to_foot', models.FloatField()),
                ('v_all_to_litr', models.FloatField()),
                ('h', models.FloatField()),
                ('weight', models.FloatField()),
                ('n_door', models.IntegerField()),
                ('n_floor', models.IntegerField()),
                ('productshenas', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.AlterField(
            model_name='product',
            name='name_class',
            field=models.CharField(choices=[('Pooshak', 'پوشاک'), ('Phone', 'موبایل'), ('System', 'سیستم'), ('TV', 'تلوزیون'), ('Laundry', 'لبتسشویی'), ('Refrigerator', 'یخچال'), ('Headset', 'هندزفری و ایر پاد'), ('Bag', 'کیف و کاور لپ تاپ'), ('Cover', 'کاور گوشی')], default='System', max_length=30, verbose_name='نام کلاس'),
        ),
        migrations.AddField(
            model_name='refrigerator',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
