# Generated by Django 4.1.3 on 2023-02-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_refrigerator_delete_bag_delete_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('Suitable', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('stracture', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('Surface_coverage', models.TextField(blank=True, null=True)),
                ('Ability', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('Suitable', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('ability', models.TextField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
