# Generated by Django 4.1.3 on 2023-02-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_cover_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('quaity_image', models.CharField(max_length=100, verbose_name='کیفیت تصویر')),
                ('resolvation', models.CharField(max_length=100, verbose_name='رزولویشن عکس')),
                ('size', models.FloatField(verbose_name='اندازه صفحه')),
                ('speaker_power', models.FloatField(verbose_name='توان بلندگو')),
                ('Aspect_ratio', models.FloatField(verbose_name='نسبت تصویر')),
                ('source_energy', models.CharField(max_length=100, verbose_name='منبع انرژی')),
                ('n_usb', models.IntegerField(verbose_name='تعداد usb')),
                ('n_hdmi', models.IntegerField(verbose_name='تعداد hdmi')),
                ('type_screen', models.CharField(max_length=100, verbose_name='نوع صفحه نمایش')),
                ('type_leg', models.CharField(max_length=100, verbose_name='نوع پایه')),
                ('descript', models.CharField(max_length=100, verbose_name='سایر توضیحات')),
                ('productshenas', models.CharField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('sex_body', models.CharField(max_length=100, verbose_name='جنس بدنه')),
                ('n_flames', models.IntegerField(verbose_name='تعداد شعله')),
                ('place_cooker', models.CharField(max_length=100, verbose_name='مکان شعله پز')),
                ('height', models.FloatField(verbose_name='ارتفاع')),
                ('sex_network', models.CharField(max_length=100, verbose_name='جنس شبکه')),
                ('productshenas', models.CharField(max_length=100, verbose_name='شناسه محصول')),
                ('sim_lenght', models.CharField(max_length=100, verbose_name='ظول سیم')),
                ('ability', models.TextField(blank=True, verbose_name='سایر قابلیت ها')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('kind_sad', models.CharField(max_length=100)),
                ('rotation_speed', models.CharField(max_length=100)),
                ('categorize_color', models.CharField(max_length=100)),
                ('capcity', models.FloatField()),
                ('type_motor', models.CharField(max_length=100)),
                ('h', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('boad', models.CharField(max_length=100)),
                ('productshenas', models.CharField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
