# Generated by Django 4.1.3 on 2023-02-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_tv_oven_laundry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_class',
            field=models.CharField(choices=[('Pooshak', 'پوشاک'), ('Phone', 'موبایل'), ('System', 'سیستم'), ('TV', 'تلوزیون'), ('Laundry', 'لبتسشویی'), ('Refrigerator', 'یخچال'), ('Headset', 'هندزفری و ایر پاد'), ('Bag', 'کیف و کاور لپ تاپ'), ('Cover', 'کاور گوشی'), ('Oven', 'اجاق')], default='System', max_length=30, verbose_name='نام کلاس'),
        ),
    ]
