# Generated by Django 4.1.3 on 2023-02-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_alter_product_name_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='capcity',
            field=models.CharField(max_length=100),
        ),
    ]
