# Generated by Django 4.1.3 on 2023-02-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_alter_laundry_capcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerator',
            name='width',
            field=models.CharField(blank=True, default=True, max_length=20, verbose_name='پهنا'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='boad',
            field=models.CharField(max_length=100, verbose_name='ابعاد'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='capcity',
            field=models.CharField(max_length=100, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='categorize_color',
            field=models.CharField(max_length=100, verbose_name='طبقه بندی رنگی'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='h',
            field=models.CharField(max_length=100, verbose_name='عمق'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='height',
            field=models.CharField(max_length=100, verbose_name='ارتفاع'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='kind_sad',
            field=models.CharField(max_length=100, verbose_name='نوع مخزن'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='productshenas',
            field=models.CharField(max_length=100, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='rotation_speed',
            field=models.CharField(max_length=100, verbose_name='سرعت چرخش موتور'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='type_motor',
            field=models.CharField(max_length=100, verbose_name='نوع موتور'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='width',
            field=models.CharField(max_length=100, verbose_name='پهنا'),
        ),
        migrations.AlterField(
            model_name='oven',
            name='height',
            field=models.CharField(max_length=100, verbose_name='ارتفاع'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='V_freeze',
            field=models.CharField(max_length=20, verbose_name='گنجایش به فریز'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='chart_energy',
            field=models.CharField(max_length=1, verbose_name='نمودار انرژی'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='foot',
            field=models.CharField(max_length=20, verbose_name='فوت'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='h',
            field=models.CharField(max_length=20, verbose_name='عمق'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='height',
            field=models.CharField(max_length=20, verbose_name='ارتفاع'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='model',
            field=models.CharField(max_length=100, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='n_door',
            field=models.IntegerField(verbose_name='تعداد در'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='n_floor',
            field=models.IntegerField(verbose_name='تعداد طبقه'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='productshenas',
            field=models.CharField(max_length=100, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='type',
            field=models.CharField(max_length=20, verbose_name='نوع یخچال'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='type_translate_barfak',
            field=models.CharField(max_length=100, verbose_name='نوع مقاومت در برابر برفک'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='v_Refrigerator',
            field=models.CharField(max_length=20, verbose_name='گنجایش به یخچال'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='v_all_to_foot',
            field=models.CharField(max_length=20, verbose_name='گنجایش کل به فوت'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='v_all_to_litr',
            field=models.CharField(max_length=20, verbose_name='گنجایش کل به لیتر'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='weight',
            field=models.CharField(max_length=20, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='Aspect_ratio',
            field=models.CharField(max_length=100, verbose_name='نسبت تصویر'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='productshenas',
            field=models.CharField(max_length=100, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='speaker_power',
            field=models.CharField(max_length=100, verbose_name='توان بلندگو'),
        ),
    ]
