# Generated by Django 4.1.3 on 2023-02-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_refrigerator_width_alter_laundry_boad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='version_system',
        ),
        migrations.AlterField(
            model_name='bag',
            name='Suitable',
            field=models.CharField(max_length=100, verbose_name='مناسب برای'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='ability',
            field=models.TextField(blank=True, null=True, verbose_name='قابلیت'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='model',
            field=models.CharField(max_length=100, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bag',
            name='weight',
            field=models.CharField(max_length=100, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='Ability',
            field=models.TextField(blank=True, verbose_name='قابلیت '),
        ),
        migrations.AlterField(
            model_name='cover',
            name='Suitable',
            field=models.CharField(max_length=100, verbose_name='مناسب برای'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='Surface_coverage',
            field=models.TextField(blank=True, null=True, verbose_name='پوشش سطح'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='model',
            field=models.CharField(max_length=100, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='stracture',
            field=models.CharField(max_length=20, verbose_name='ساختار'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='weight',
            field=models.CharField(max_length=20, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='hard',
            field=models.IntegerField(verbose_name='ظرفیت هارد'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='included_items',
            field=models.TextField(verbose_name='اقلام همراه'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number_sim',
            field=models.IntegerField(verbose_name='تعداد سیم'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram_number',
            field=models.IntegerField(verbose_name='ظرفیت رم'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='resolvation_image',
            field=models.CharField(max_length=100, verbose_name='رزولیشن عکس'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_technology',
            field=models.CharField(max_length=100, verbose_name='تکنولوژی صفحه'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='size_screen',
            field=models.CharField(max_length=100, verbose_name='انندازه صفحه'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='system_type',
            field=models.CharField(max_length=20, verbose_name='نوغ سیستم عامل'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='weight',
            field=models.CharField(max_length=20, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='pooshak',
            name='Maintenance',
            field=models.TextField(blank=True, null=True, verbose_name='شرایط نگهداری'),
        ),
        migrations.AlterField(
            model_name='pooshak',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='pooshak',
            name='model',
            field=models.CharField(blank=True, max_length=200, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='pooshak',
            name='sex',
            field=models.CharField(default='', max_length=100, verbose_name='جنس'),
        ),
        migrations.AlterField(
            model_name='system',
            name='capcity_hard',
            field=models.IntegerField(verbose_name='ظرفیت هارد'),
        ),
        migrations.AlterField(
            model_name='system',
            name='connect_door',
            field=models.CharField(max_length=100, verbose_name='تعداد درگاه ها ارتباطی'),
        ),
        migrations.AlterField(
            model_name='system',
            name='guarantee_time',
            field=models.CharField(max_length=100, verbose_name='گارانتی'),
        ),
        migrations.AlterField(
            model_name='system',
            name='model',
            field=models.CharField(max_length=100, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='system',
            name='number_port',
            field=models.IntegerField(default=0, verbose_name='تعداد پورت'),
        ),
        migrations.AlterField(
            model_name='system',
            name='size_screen',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_func',
            field=models.CharField(max_length=100, verbose_name='سیستم عامل'),
        ),
        migrations.AlterField(
            model_name='system',
            name='webcam',
            field=models.BooleanField(default=True, verbose_name='وبکم'),
        ),
        migrations.AlterField(
            model_name='system',
            name='weight',
            field=models.CharField(max_length=100, verbose_name='وزن'),
        ),
    ]
