# Generated by Django 4.1.3 on 2023-03-09 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_remove_comment_email_comment_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorize_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cate_name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.categorize_products', verbose_name='زیر مجموعه:')),
            ],
        ),
    ]
