# Generated by Django 4.1.3 on 2023-03-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0038_alter_product_categorize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorize',
            field=models.CharField(choices=[('Digital', 'کالای دیجیتال'), ('va', 'hggg'), ('digital_cart', 'کالای دیجیتال'), ('mobile', 'گوشی'), ('lavazem', 'لوازم خانگی'), ('lundry', 'یخچال')], default='Digital', max_length=20),
        ),
    ]
