# Generated by Django 4.1.3 on 2023-03-09 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0040_alter_product_categorize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategorize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='image_cate')),
                ('cate_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.categorize_products')),
            ],
        ),
    ]
