# Generated by Django 4.1.3 on 2023-03-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0044_alter_product_categorize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorize',
            field=models.CharField(choices=[('Digital', 'کالای دیجیتال'), ('Phone', 'موبایل'), ('Appliances', 'لوازم خانگی'), ('Pooshak', 'پوشاک'), ('System', 'لپ تاپ'), ('TV', 'تلوزیون'), ('Laundry', 'لباسشویی'), ('Headset', 'هندزفری و هدست'), ('Bag', 'کیف'), ('Cover', 'کاور'), ('Oven', 'اجاق گاز'), ('Scarf', 'روسری شال'), ('Shoes', 'کفش'), ('Manteu', 'مانتو'), ('Coat', 'پالتو'), ('Refrigerator', 'یخچال')], default='Digital', max_length=20),
        ),
    ]
