# Generated by Django 4.1.3 on 2023-03-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_alter_product_categorize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_all',
        ),
    ]
