# Generated by Django 4.1.3 on 2023-03-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0046_remove_product_count_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_product')),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AutherImage', to='Product.product')),
            ],
        ),
    ]
