# Generated by Django 4.1.3 on 2023-03-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0047_imageproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('url_field', models.CharField(max_length=100)),
                ('image_field', models.ImageField(blank=True, default=True, upload_to='image_brand')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
