# Generated by Django 4.1.3 on 2023-03-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0049_product_brand_p'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': 'کیف', 'verbose_name_plural': 'کیف ها'},
        ),
        migrations.AlterModelOptions(
            name='brandproduct',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='categorize_products',
            options={'verbose_name': 'دسته بندی محصول', 'verbose_name_plural': 'دسته بندی های محصولات'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name': 'کاور', 'verbose_name_plural': 'کاورها'},
        ),
        migrations.AlterModelOptions(
            name='detailpooshak',
            options={'verbose_name': 'جزئیات لباس', 'verbose_name_plural': 'جزئیات لباس ها'},
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='laundry',
            options={'verbose_name': 'لباسشویی', 'verbose_name_plural': 'لباسشویی ها'},
        ),
        migrations.AlterModelOptions(
            name='oven',
            options={'verbose_name': 'اجاق گاز', 'verbose_name_plural': 'اجاق گازها'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'گوشی', 'verbose_name_plural': 'گوشی ها'},
        ),
        migrations.AlterModelOptions(
            name='pooshak',
            options={'verbose_name': 'لباس', 'verbose_name_plural': 'لباس ها'},
        ),
        migrations.AlterModelOptions(
            name='refrigerator',
            options={'verbose_name': 'یخچال', 'verbose_name_plural': 'یخچال ها'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name': 'تلوزیون', 'verbose_name_plural': 'تلوزیون ها'},
        ),
    ]
