# Generated by Django 4.1.3 on 2023-03-15 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0050_alter_bag_options_alter_brandproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecategorize',
            options={'verbose_name': 'تصویر دسته بندی', 'verbose_name_plural': 'تصاویر دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='bag',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
        migrations.AlterField(
            model_name='brandproduct',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='brandproduct',
            name='image_field',
            field=models.ImageField(blank=True, default=True, upload_to='image_brand', verbose_name='عکس برند'),
        ),
        migrations.AlterField(
            model_name='brandproduct',
            name='url_field',
            field=models.CharField(max_length=100, verbose_name='عنوان برند'),
        ),
        migrations.AlterField(
            model_name='categorize_products',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='فامیلی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='massege',
            field=models.TextField(verbose_name='پبام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
        migrations.AlterField(
            model_name='detailpooshak',
            name='count',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='detailpooshak',
            name='detail_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pooshak', to='Product.detailproduct', verbose_name='جزئیات محصول'),
        ),
        migrations.AlterField(
            model_name='detailpooshak',
            name='size',
            field=models.CharField(max_length=100, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='detailproduct',
            name='count',
            field=models.IntegerField(null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='imagecategorize',
            name='cate_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagecate', to='Product.categorize_products', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='imagecategorize',
            name='image',
            field=models.ImageField(default='', upload_to='image_cate', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to='image_product', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AutherImage', to='Product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='laundry',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
        migrations.AlterField(
            model_name='oven',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوططه'),
        ),
        migrations.AlterField(
            model_name='pooshak',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_p',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_product', to='Product.brandproduct', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorize',
            field=models.CharField(choices=[('Digital', 'کالای دیجیتال'), ('Phone', 'موبایل'), ('Appliances', 'لوازم خانگی'), ('Pooshak', 'پوشاک'), ('System', 'لپ تاپ'), ('TV', 'تلوزیون'), ('Laundry', 'لباسشویی'), ('Headset', 'هندزفری و هدست'), ('Bag', 'کیف'), ('Cover', 'کاور'), ('Oven', 'اجاق گاز'), ('Scarf', 'روسری شال'), ('Shoes', 'کفش'), ('Manteu', 'مانتو'), ('Coat', 'پالتو'), ('Refrigerator', 'یخچال')], default='Digital', max_length=20, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_buy',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='refrigerator',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
        migrations.AlterField(
            model_name='system',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='محصول مربوطه'),
        ),
    ]
