# Generated by Django 4.1.3 on 2023-02-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_job_user_natiional_code_user_re_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ایمیل جایگزین'),
        ),
    ]
