# Generated by Django 4.1.3 on 2023-02-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
