# Generated by Django 4.1.3 on 2023-03-02 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_user_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('about_us', models.TextField(verbose_name='درباره ما')),
                ('logo', models.ImageField(blank=True, upload_to='contact_us', verbose_name='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gap', models.CharField(max_length=200)),
                ('anable', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('address_contact', models.CharField(max_length=300, verbose_name='ادرس')),
                ('email', models.CharField(max_length=300, verbose_name='ایمیل')),
                ('fax', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('id_insta', models.URLField()),
                ('id_soroosh', models.URLField()),
                ('id_bale', models.URLField()),
                ('image_address', models.ImageField(upload_to='contact_us')),
            ],
        ),
        migrations.CreateModel(
            name='MessageToAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
