# Generated by Django 4.1.3 on 2023-03-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_about_us_contact_us_messagetoadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Us',
        ),
        migrations.DeleteModel(
            name='Contact_Us',
        ),
        migrations.DeleteModel(
            name='MessageToAdmin',
        ),
    ]
