# Generated by Django 4.1.3 on 2023-02-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilorder',
            name='order_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermain', to='Order.order'),
        ),
    ]
