# Generated by Django 4.1.3 on 2023-02-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_system_date_create_comment_date_comment_time'),
        ('Order', '0002_alter_detilorder_order_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilorder',
            name='detail_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.detailproduct'),
        ),
    ]
