# Generated by Django 4.1.3 on 2023-02-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'پرداخت نشده'), (1, 'پرداخت شده'), (2, 'مرجوع شده')], default=0),
        ),
    ]
