# Generated by Django 4.1.3 on 2023-02-12 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_remove_detilorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
