# Generated by Django 4.1.3 on 2023-03-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_address_post_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
