# Generated by Django 4.1.3 on 2023-03-15 18:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0049_product_brand_p'),
        ('Order', '0012_delete_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AlterModelOptions(
            name='detilorder',
            options={'verbose_name': 'چزئیات سفارش', 'verbose_name_plural': 'جزِئیات سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'محصول پسندیده شده', 'verbose_name_plural': 'محصولات پسندیده شده'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useraddress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='detilorder',
            name='count',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='detilorder',
            name='detail_pooshak',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.detailpooshak', verbose_name='جزئیات پوشاک'),
        ),
        migrations.AlterField(
            model_name='detilorder',
            name='detail_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.detailproduct', verbose_name='جزئیات محصول'),
        ),
        migrations.AlterField(
            model_name='detilorder',
            name='order_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermain', to='Order.order', verbose_name='سبد خرید اصلی'),
        ),
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_like', to='Product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderaddres', to='Order.address', verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'پرداخت نشده'), (1, 'پرداخت شده'), (2, 'مرجوع شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorder', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
