# Generated by Django 4.1.3 on 2023-03-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_alter_address_options_alter_detilorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='TrackingCode',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
